### ISSUE TITLE
yoman required fields...

### ISSUE THREAD

**Issue by pstephenwille** [chentsulin/generator-redux-app#58]
Not sure if this is a problem with my set up, or your generator, but just in case, here it is:

I was unable to use the Yoman generator because it errored out when I didn't provide a user name, or website URL.   Entering dummy values for those fields gives me a NodeJs error:
             ERROR in ./src/createRoutes.js
             File/Program node, we can't possibly find a statement parent to this

**Comment by chentsulin** [comment]
Try remove `react-optimize` from .babelrc, maybe it could help.

**Comment by chentsulin** [comment]
Can't reproduce with latest `v0.21.0`

https://github.com/chentsulin/generator-redux-app/releases/tag/v0.21.0
