### ISSUE TITLE
supporting html-webpack-plugin

### ISSUE THREAD

**Issue by yosit** [chentsulin/generator-redux-app#6]
Hi,
Awesome work!

I've added html-webpack-plugin - but I noticed the npm start doesn't really run wepback.
This is the plugins section on webpack.config.js 

```
plugins: [
    new HtmlwebpackPlugin(),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.DefinePlugin({
      '__DEVTOOLS__': true,
      'process.env': JSON.stringify('development')
  })
],
```

I had to change the "build" in scripts in package.json to:

```
"start": "webpack && node server.js",
```

Also in server.js I changed the index.html to the one that is generated:

```
res.sendFile(path.join(__dirname, 'dist/index.html'));
```

and  index.js now has this:

```
const root = document.createElement('div');
document.body.appendChild(root);
ReactDOM.render(<Root history={history} />,root);
```

Am I missing something - is there a reason why you wouldn't want to run webpack before starting to develop and launching the dev server?

I believe html-webpack-plugin would minimize the need to maintain index.html.

**Comment by chentsulin** [comment]
Launching the dev server will also run webpack build (webpack-dev-middleware), wouldn't it? I use almost the same config with https://github.com/gaearon/react-transform-boilerplate.

I haven't use `html-webpack-plugin` before, PR welcome.
